name: Auto Release Main
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2 
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          package-name: wabbajack
          release-type: simple
  windows-x86_64:
    runs-on: windows-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: |
          mkdir release
          dotnet restore
          dotnet publish Wabbajack.App.Wpf\Wabbajack.App.Wpf.csproj --runtime win-x64 --configuration Release /p:Platform=x64 -o .\release\app /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained /p:DebugType=embedded
          dotnet publish Wabbajack.CLI\Wabbajack.CLI.csproj --runtime win-x64 --configuration Release /p:Platform=x64 -o .\release\app --self-contained /p:DebugType=embedded
      - name: Package
        run: |
          cd release
          7z a -tzip ..\release.zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: wabbajack-${{ needs.release.outputs.tag_name }}-windows-x86_64.zip
          asset_content_type: application/zip
          asset_path: release.zip
          upload_url: ${{ needs.release.outputs.upload_url }}
